// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package schema

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testCardPackTypes(t *testing.T) {
	t.Parallel()

	query := CardPackTypes()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testCardPackTypesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CardPackType{}
	if err = randomize.Struct(seed, o, cardPackTypeDBTypes, true, cardPackTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CardPackTypes().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCardPackTypesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CardPackType{}
	if err = randomize.Struct(seed, o, cardPackTypeDBTypes, true, cardPackTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := CardPackTypes().DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CardPackTypes().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCardPackTypesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CardPackType{}
	if err = randomize.Struct(seed, o, cardPackTypeDBTypes, true, cardPackTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CardPackTypeSlice{o}

	if rowsAff, err := slice.DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := CardPackTypes().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCardPackTypesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CardPackType{}
	if err = randomize.Struct(seed, o, cardPackTypeDBTypes, true, cardPackTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := CardPackTypeExists(tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if CardPackType exists: %s", err)
	}
	if !e {
		t.Errorf("Expected CardPackTypeExists to return true, but got false.")
	}
}

func testCardPackTypesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CardPackType{}
	if err = randomize.Struct(seed, o, cardPackTypeDBTypes, true, cardPackTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	cardPackTypeFound, err := FindCardPackType(tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if cardPackTypeFound == nil {
		t.Error("want a record, got nil")
	}
}

func testCardPackTypesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CardPackType{}
	if err = randomize.Struct(seed, o, cardPackTypeDBTypes, true, cardPackTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = CardPackTypes().Bind(nil, tx, o); err != nil {
		t.Error(err)
	}
}

func testCardPackTypesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CardPackType{}
	if err = randomize.Struct(seed, o, cardPackTypeDBTypes, true, cardPackTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := CardPackTypes().One(tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testCardPackTypesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	cardPackTypeOne := &CardPackType{}
	cardPackTypeTwo := &CardPackType{}
	if err = randomize.Struct(seed, cardPackTypeOne, cardPackTypeDBTypes, false, cardPackTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}
	if err = randomize.Struct(seed, cardPackTypeTwo, cardPackTypeDBTypes, false, cardPackTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = cardPackTypeOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = cardPackTypeTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CardPackTypes().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testCardPackTypesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	cardPackTypeOne := &CardPackType{}
	cardPackTypeTwo := &CardPackType{}
	if err = randomize.Struct(seed, cardPackTypeOne, cardPackTypeDBTypes, false, cardPackTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}
	if err = randomize.Struct(seed, cardPackTypeTwo, cardPackTypeDBTypes, false, cardPackTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = cardPackTypeOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = cardPackTypeTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CardPackTypes().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testCardPackTypesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CardPackType{}
	if err = randomize.Struct(seed, o, cardPackTypeDBTypes, true, cardPackTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CardPackTypes().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCardPackTypesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CardPackType{}
	if err = randomize.Struct(seed, o, cardPackTypeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Whitelist(cardPackTypeColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := CardPackTypes().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCardPackTypeToManyAssignedCardPacks(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a CardPackType
	var b, c AssignedCardPack

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, cardPackTypeDBTypes, true, cardPackTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, assignedCardPackDBTypes, false, assignedCardPackColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, assignedCardPackDBTypes, false, assignedCardPackColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.CardPackTypeID = a.ID
	c.CardPackTypeID = a.ID

	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.AssignedCardPacks().All(tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.CardPackTypeID == b.CardPackTypeID {
			bFound = true
		}
		if v.CardPackTypeID == c.CardPackTypeID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := CardPackTypeSlice{&a}
	if err = a.L.LoadAssignedCardPacks(tx, false, (*[]*CardPackType)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.AssignedCardPacks); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.AssignedCardPacks = nil
	if err = a.L.LoadAssignedCardPacks(tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.AssignedCardPacks); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testCardPackTypeToManyAddOpAssignedCardPacks(t *testing.T) {
	var err error

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()

	var a CardPackType
	var b, c, d, e AssignedCardPack

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, cardPackTypeDBTypes, false, strmangle.SetComplement(cardPackTypePrimaryKeyColumns, cardPackTypeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*AssignedCardPack{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, assignedCardPackDBTypes, false, strmangle.SetComplement(assignedCardPackPrimaryKeyColumns, assignedCardPackColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*AssignedCardPack{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddAssignedCardPacks(tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.CardPackTypeID {
			t.Error("foreign key was wrong value", a.ID, first.CardPackTypeID)
		}
		if a.ID != second.CardPackTypeID {
			t.Error("foreign key was wrong value", a.ID, second.CardPackTypeID)
		}

		if first.R.CardPackType != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.CardPackType != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.AssignedCardPacks[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.AssignedCardPacks[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.AssignedCardPacks().Count(tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testCardPackTypesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CardPackType{}
	if err = randomize.Struct(seed, o, cardPackTypeDBTypes, true, cardPackTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testCardPackTypesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CardPackType{}
	if err = randomize.Struct(seed, o, cardPackTypeDBTypes, true, cardPackTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CardPackTypeSlice{o}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}

func testCardPackTypesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &CardPackType{}
	if err = randomize.Struct(seed, o, cardPackTypeDBTypes, true, cardPackTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := CardPackTypes().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	cardPackTypeDBTypes = map[string]string{`ID`: `uuid`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`, `Name`: `character varying`, `Description`: `text`, `Image`: `text`, `Tier1`: `jsonb`, `Tier2`: `jsonb`, `Tier3`: `jsonb`, `Tier4`: `jsonb`, `Tier5`: `jsonb`, `PackLimits`: `integer`, `CardPackCode`: `character varying`, `Rarities`: `jsonb`, `StarRatings`: `jsonb`, `Collection`: `character varying`}
	_                   = bytes.MinRead
)

func testCardPackTypesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(cardPackTypePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(cardPackTypeAllColumns) == len(cardPackTypePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CardPackType{}
	if err = randomize.Struct(seed, o, cardPackTypeDBTypes, true, cardPackTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CardPackTypes().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, cardPackTypeDBTypes, true, cardPackTypePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	if rowsAff, err := o.Update(tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testCardPackTypesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(cardPackTypeAllColumns) == len(cardPackTypePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &CardPackType{}
	if err = randomize.Struct(seed, o, cardPackTypeDBTypes, true, cardPackTypeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := CardPackTypes().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, cardPackTypeDBTypes, true, cardPackTypePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(cardPackTypeAllColumns, cardPackTypePrimaryKeyColumns) {
		fields = cardPackTypeAllColumns
	} else {
		fields = strmangle.SetComplement(
			cardPackTypeAllColumns,
			cardPackTypePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := CardPackTypeSlice{o}
	if rowsAff, err := slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testCardPackTypesUpsert(t *testing.T) {
	t.Parallel()

	if len(cardPackTypeAllColumns) == len(cardPackTypePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := CardPackType{}
	if err = randomize.Struct(seed, &o, cardPackTypeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CardPackType: %s", err)
	}

	count, err := CardPackTypes().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, cardPackTypeDBTypes, false, cardPackTypePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize CardPackType struct: %s", err)
	}

	if err = o.Upsert(tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert CardPackType: %s", err)
	}

	count, err = CardPackTypes().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
