// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package schema

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// ChatMessage is an object representing the database table.
type ChatMessage struct {
	ID        string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Message   string    `boil:"message" json:"message" toml:"message" yaml:"message"`
	RoomID    string    `boil:"room_id" json:"room_id" toml:"room_id" yaml:"room_id"`
	SenderID  string    `boil:"sender_id" json:"sender_id" toml:"sender_id" yaml:"sender_id"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *chatMessageR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L chatMessageL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ChatMessageColumns = struct {
	ID        string
	Message   string
	RoomID    string
	SenderID  string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	Message:   "message",
	RoomID:    "room_id",
	SenderID:  "sender_id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var ChatMessageTableColumns = struct {
	ID        string
	Message   string
	RoomID    string
	SenderID  string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "chat_messages.id",
	Message:   "chat_messages.message",
	RoomID:    "chat_messages.room_id",
	SenderID:  "chat_messages.sender_id",
	CreatedAt: "chat_messages.created_at",
	UpdatedAt: "chat_messages.updated_at",
}

// Generated where

var ChatMessageWhere = struct {
	ID        whereHelperstring
	Message   whereHelperstring
	RoomID    whereHelperstring
	SenderID  whereHelperstring
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	ID:        whereHelperstring{field: "\"chat_messages\".\"id\""},
	Message:   whereHelperstring{field: "\"chat_messages\".\"message\""},
	RoomID:    whereHelperstring{field: "\"chat_messages\".\"room_id\""},
	SenderID:  whereHelperstring{field: "\"chat_messages\".\"sender_id\""},
	CreatedAt: whereHelpertime_Time{field: "\"chat_messages\".\"created_at\""},
	UpdatedAt: whereHelpertime_Time{field: "\"chat_messages\".\"updated_at\""},
}

// ChatMessageRels is where relationship names are stored.
var ChatMessageRels = struct {
	Room   string
	Sender string
}{
	Room:   "Room",
	Sender: "Sender",
}

// chatMessageR is where relationships are stored.
type chatMessageR struct {
	Room   *ChatRoom `boil:"Room" json:"Room" toml:"Room" yaml:"Room"`
	Sender *User     `boil:"Sender" json:"Sender" toml:"Sender" yaml:"Sender"`
}

// NewStruct creates a new relationship struct
func (*chatMessageR) NewStruct() *chatMessageR {
	return &chatMessageR{}
}

func (r *chatMessageR) GetRoom() *ChatRoom {
	if r == nil {
		return nil
	}
	return r.Room
}

func (r *chatMessageR) GetSender() *User {
	if r == nil {
		return nil
	}
	return r.Sender
}

// chatMessageL is where Load methods for each relationship are stored.
type chatMessageL struct{}

var (
	chatMessageAllColumns            = []string{"id", "message", "room_id", "sender_id", "created_at", "updated_at"}
	chatMessageColumnsWithoutDefault = []string{"id", "message", "room_id", "sender_id", "created_at", "updated_at"}
	chatMessageColumnsWithDefault    = []string{}
	chatMessagePrimaryKeyColumns     = []string{"id"}
	chatMessageGeneratedColumns      = []string{}
)

type (
	// ChatMessageSlice is an alias for a slice of pointers to ChatMessage.
	// This should almost always be used instead of []ChatMessage.
	ChatMessageSlice []*ChatMessage

	chatMessageQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	chatMessageType                 = reflect.TypeOf(&ChatMessage{})
	chatMessageMapping              = queries.MakeStructMapping(chatMessageType)
	chatMessagePrimaryKeyMapping, _ = queries.BindMapping(chatMessageType, chatMessageMapping, chatMessagePrimaryKeyColumns)
	chatMessageInsertCacheMut       sync.RWMutex
	chatMessageInsertCache          = make(map[string]insertCache)
	chatMessageUpdateCacheMut       sync.RWMutex
	chatMessageUpdateCache          = make(map[string]updateCache)
	chatMessageUpsertCacheMut       sync.RWMutex
	chatMessageUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single chatMessage record from the query.
func (q chatMessageQuery) One(exec boil.Executor) (*ChatMessage, error) {
	o := &ChatMessage{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "schema: failed to execute a one query for chat_messages")
	}

	return o, nil
}

// All returns all ChatMessage records from the query.
func (q chatMessageQuery) All(exec boil.Executor) (ChatMessageSlice, error) {
	var o []*ChatMessage

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "schema: failed to assign all query results to ChatMessage slice")
	}

	return o, nil
}

// Count returns the count of all ChatMessage records in the query.
func (q chatMessageQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "schema: failed to count chat_messages rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q chatMessageQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "schema: failed to check if chat_messages exists")
	}

	return count > 0, nil
}

// Room pointed to by the foreign key.
func (o *ChatMessage) Room(mods ...qm.QueryMod) chatRoomQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.RoomID),
	}

	queryMods = append(queryMods, mods...)

	return ChatRooms(queryMods...)
}

// Sender pointed to by the foreign key.
func (o *ChatMessage) Sender(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.SenderID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadRoom allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (chatMessageL) LoadRoom(e boil.Executor, singular bool, maybeChatMessage interface{}, mods queries.Applicator) error {
	var slice []*ChatMessage
	var object *ChatMessage

	if singular {
		var ok bool
		object, ok = maybeChatMessage.(*ChatMessage)
		if !ok {
			object = new(ChatMessage)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeChatMessage)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeChatMessage))
			}
		}
	} else {
		s, ok := maybeChatMessage.(*[]*ChatMessage)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeChatMessage)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeChatMessage))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &chatMessageR{}
		}
		args[object.RoomID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &chatMessageR{}
			}

			args[obj.RoomID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`chat_rooms`),
		qm.WhereIn(`chat_rooms.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ChatRoom")
	}

	var resultSlice []*ChatRoom
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ChatRoom")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for chat_rooms")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for chat_rooms")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Room = foreign
		if foreign.R == nil {
			foreign.R = &chatRoomR{}
		}
		foreign.R.RoomChatMessages = append(foreign.R.RoomChatMessages, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.RoomID == foreign.ID {
				local.R.Room = foreign
				if foreign.R == nil {
					foreign.R = &chatRoomR{}
				}
				foreign.R.RoomChatMessages = append(foreign.R.RoomChatMessages, local)
				break
			}
		}
	}

	return nil
}

// LoadSender allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (chatMessageL) LoadSender(e boil.Executor, singular bool, maybeChatMessage interface{}, mods queries.Applicator) error {
	var slice []*ChatMessage
	var object *ChatMessage

	if singular {
		var ok bool
		object, ok = maybeChatMessage.(*ChatMessage)
		if !ok {
			object = new(ChatMessage)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeChatMessage)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeChatMessage))
			}
		}
	} else {
		s, ok := maybeChatMessage.(*[]*ChatMessage)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeChatMessage)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeChatMessage))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &chatMessageR{}
		}
		args[object.SenderID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &chatMessageR{}
			}

			args[obj.SenderID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Sender = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.SenderChatMessages = append(foreign.R.SenderChatMessages, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SenderID == foreign.ID {
				local.R.Sender = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.SenderChatMessages = append(foreign.R.SenderChatMessages, local)
				break
			}
		}
	}

	return nil
}

// SetRoom of the chatMessage to the related item.
// Sets o.R.Room to related.
// Adds o to related.R.RoomChatMessages.
func (o *ChatMessage) SetRoom(exec boil.Executor, insert bool, related *ChatRoom) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"chat_messages\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"room_id"}),
		strmangle.WhereClause("\"", "\"", 2, chatMessagePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.RoomID = related.ID
	if o.R == nil {
		o.R = &chatMessageR{
			Room: related,
		}
	} else {
		o.R.Room = related
	}

	if related.R == nil {
		related.R = &chatRoomR{
			RoomChatMessages: ChatMessageSlice{o},
		}
	} else {
		related.R.RoomChatMessages = append(related.R.RoomChatMessages, o)
	}

	return nil
}

// SetSender of the chatMessage to the related item.
// Sets o.R.Sender to related.
// Adds o to related.R.SenderChatMessages.
func (o *ChatMessage) SetSender(exec boil.Executor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"chat_messages\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"sender_id"}),
		strmangle.WhereClause("\"", "\"", 2, chatMessagePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SenderID = related.ID
	if o.R == nil {
		o.R = &chatMessageR{
			Sender: related,
		}
	} else {
		o.R.Sender = related
	}

	if related.R == nil {
		related.R = &userR{
			SenderChatMessages: ChatMessageSlice{o},
		}
	} else {
		related.R.SenderChatMessages = append(related.R.SenderChatMessages, o)
	}

	return nil
}

// ChatMessages retrieves all the records using an executor.
func ChatMessages(mods ...qm.QueryMod) chatMessageQuery {
	mods = append(mods, qm.From("\"chat_messages\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"chat_messages\".*"})
	}

	return chatMessageQuery{q}
}

// FindChatMessage retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindChatMessage(exec boil.Executor, iD string, selectCols ...string) (*ChatMessage, error) {
	chatMessageObj := &ChatMessage{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"chat_messages\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, chatMessageObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "schema: unable to select from chat_messages")
	}

	return chatMessageObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ChatMessage) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("schema: no chat_messages provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	if o.UpdatedAt.IsZero() {
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(chatMessageColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	chatMessageInsertCacheMut.RLock()
	cache, cached := chatMessageInsertCache[key]
	chatMessageInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			chatMessageAllColumns,
			chatMessageColumnsWithDefault,
			chatMessageColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(chatMessageType, chatMessageMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(chatMessageType, chatMessageMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"chat_messages\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"chat_messages\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "schema: unable to insert into chat_messages")
	}

	if !cached {
		chatMessageInsertCacheMut.Lock()
		chatMessageInsertCache[key] = cache
		chatMessageInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the ChatMessage.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ChatMessage) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt = currTime

	var err error
	key := makeCacheKey(columns, nil)
	chatMessageUpdateCacheMut.RLock()
	cache, cached := chatMessageUpdateCache[key]
	chatMessageUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			chatMessageAllColumns,
			chatMessagePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("schema: unable to update chat_messages, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"chat_messages\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, chatMessagePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(chatMessageType, chatMessageMapping, append(wl, chatMessagePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "schema: unable to update chat_messages row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "schema: failed to get rows affected by update for chat_messages")
	}

	if !cached {
		chatMessageUpdateCacheMut.Lock()
		chatMessageUpdateCache[key] = cache
		chatMessageUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q chatMessageQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "schema: unable to update all for chat_messages")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "schema: unable to retrieve rows affected for chat_messages")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ChatMessageSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("schema: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chatMessagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"chat_messages\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, chatMessagePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "schema: unable to update all in chatMessage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "schema: unable to retrieve rows affected all in update all chatMessage")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ChatMessage) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("schema: no chat_messages provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.IsZero() {
		o.CreatedAt = currTime
	}
	o.UpdatedAt = currTime

	nzDefaults := queries.NonZeroDefaultSet(chatMessageColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	chatMessageUpsertCacheMut.RLock()
	cache, cached := chatMessageUpsertCache[key]
	chatMessageUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			chatMessageAllColumns,
			chatMessageColumnsWithDefault,
			chatMessageColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			chatMessageAllColumns,
			chatMessagePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("schema: unable to upsert chat_messages, could not build update column list")
		}

		ret := strmangle.SetComplement(chatMessageAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(chatMessagePrimaryKeyColumns) == 0 {
				return errors.New("schema: unable to upsert chat_messages, could not build conflict column list")
			}

			conflict = make([]string, len(chatMessagePrimaryKeyColumns))
			copy(conflict, chatMessagePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"chat_messages\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(chatMessageType, chatMessageMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(chatMessageType, chatMessageMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "schema: unable to upsert chat_messages")
	}

	if !cached {
		chatMessageUpsertCacheMut.Lock()
		chatMessageUpsertCache[key] = cache
		chatMessageUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single ChatMessage record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ChatMessage) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("schema: no ChatMessage provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), chatMessagePrimaryKeyMapping)
	sql := "DELETE FROM \"chat_messages\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "schema: unable to delete from chat_messages")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "schema: failed to get rows affected by delete for chat_messages")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q chatMessageQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("schema: no chatMessageQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "schema: unable to delete all from chat_messages")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "schema: failed to get rows affected by deleteall for chat_messages")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ChatMessageSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chatMessagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"chat_messages\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, chatMessagePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "schema: unable to delete all from chatMessage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "schema: failed to get rows affected by deleteall for chat_messages")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ChatMessage) Reload(exec boil.Executor) error {
	ret, err := FindChatMessage(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ChatMessageSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ChatMessageSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chatMessagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"chat_messages\".* FROM \"chat_messages\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, chatMessagePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "schema: unable to reload all in ChatMessageSlice")
	}

	*o = slice

	return nil
}

// ChatMessageExists checks if the ChatMessage row exists.
func ChatMessageExists(exec boil.Executor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"chat_messages\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "schema: unable to check if chat_messages exists")
	}

	return exists, nil
}

// Exists checks if the ChatMessage row exists.
func (o *ChatMessage) Exists(exec boil.Executor) (bool, error) {
	return ChatMessageExists(exec, o.ID)
}
