// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package schema

import (
	"bytes"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testFanclashCaches(t *testing.T) {
	t.Parallel()

	query := FanclashCaches()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testFanclashCachesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FanclashCache{}
	if err = randomize.Struct(seed, o, fanclashCacheDBTypes, true, fanclashCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := FanclashCaches().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFanclashCachesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FanclashCache{}
	if err = randomize.Struct(seed, o, fanclashCacheDBTypes, true, fanclashCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := FanclashCaches().DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := FanclashCaches().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFanclashCachesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FanclashCache{}
	if err = randomize.Struct(seed, o, fanclashCacheDBTypes, true, fanclashCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FanclashCacheSlice{o}

	if rowsAff, err := slice.DeleteAll(tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := FanclashCaches().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFanclashCachesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FanclashCache{}
	if err = randomize.Struct(seed, o, fanclashCacheDBTypes, true, fanclashCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := FanclashCacheExists(tx, o.CacheKey)
	if err != nil {
		t.Errorf("Unable to check if FanclashCache exists: %s", err)
	}
	if !e {
		t.Errorf("Expected FanclashCacheExists to return true, but got false.")
	}
}

func testFanclashCachesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FanclashCache{}
	if err = randomize.Struct(seed, o, fanclashCacheDBTypes, true, fanclashCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	fanclashCacheFound, err := FindFanclashCache(tx, o.CacheKey)
	if err != nil {
		t.Error(err)
	}

	if fanclashCacheFound == nil {
		t.Error("want a record, got nil")
	}
}

func testFanclashCachesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FanclashCache{}
	if err = randomize.Struct(seed, o, fanclashCacheDBTypes, true, fanclashCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = FanclashCaches().Bind(nil, tx, o); err != nil {
		t.Error(err)
	}
}

func testFanclashCachesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FanclashCache{}
	if err = randomize.Struct(seed, o, fanclashCacheDBTypes, true, fanclashCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := FanclashCaches().One(tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testFanclashCachesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	fanclashCacheOne := &FanclashCache{}
	fanclashCacheTwo := &FanclashCache{}
	if err = randomize.Struct(seed, fanclashCacheOne, fanclashCacheDBTypes, false, fanclashCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}
	if err = randomize.Struct(seed, fanclashCacheTwo, fanclashCacheDBTypes, false, fanclashCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = fanclashCacheOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = fanclashCacheTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := FanclashCaches().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testFanclashCachesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	fanclashCacheOne := &FanclashCache{}
	fanclashCacheTwo := &FanclashCache{}
	if err = randomize.Struct(seed, fanclashCacheOne, fanclashCacheDBTypes, false, fanclashCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}
	if err = randomize.Struct(seed, fanclashCacheTwo, fanclashCacheDBTypes, false, fanclashCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = fanclashCacheOne.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = fanclashCacheTwo.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := FanclashCaches().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testFanclashCachesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FanclashCache{}
	if err = randomize.Struct(seed, o, fanclashCacheDBTypes, true, fanclashCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := FanclashCaches().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFanclashCachesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FanclashCache{}
	if err = randomize.Struct(seed, o, fanclashCacheDBTypes, true); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Whitelist(fanclashCacheColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := FanclashCaches().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFanclashCachesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FanclashCache{}
	if err = randomize.Struct(seed, o, fanclashCacheDBTypes, true, fanclashCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(tx); err != nil {
		t.Error(err)
	}
}

func testFanclashCachesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FanclashCache{}
	if err = randomize.Struct(seed, o, fanclashCacheDBTypes, true, fanclashCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FanclashCacheSlice{o}

	if err = slice.ReloadAll(tx); err != nil {
		t.Error(err)
	}
}

func testFanclashCachesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &FanclashCache{}
	if err = randomize.Struct(seed, o, fanclashCacheDBTypes, true, fanclashCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := FanclashCaches().All(tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	fanclashCacheDBTypes = map[string]string{`CacheKey`: `character varying`, `Value`: `text`, `Expires`: `timestamp with time zone`}
	_                    = bytes.MinRead
)

func testFanclashCachesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(fanclashCachePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(fanclashCacheAllColumns) == len(fanclashCachePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &FanclashCache{}
	if err = randomize.Struct(seed, o, fanclashCacheDBTypes, true, fanclashCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := FanclashCaches().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, fanclashCacheDBTypes, true, fanclashCachePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	if rowsAff, err := o.Update(tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testFanclashCachesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(fanclashCacheAllColumns) == len(fanclashCachePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &FanclashCache{}
	if err = randomize.Struct(seed, o, fanclashCacheDBTypes, true, fanclashCacheColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := FanclashCaches().Count(tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, fanclashCacheDBTypes, true, fanclashCachePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(fanclashCacheAllColumns, fanclashCachePrimaryKeyColumns) {
		fields = fanclashCacheAllColumns
	} else {
		fields = strmangle.SetComplement(
			fanclashCacheAllColumns,
			fanclashCachePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := FanclashCacheSlice{o}
	if rowsAff, err := slice.UpdateAll(tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testFanclashCachesUpsert(t *testing.T) {
	t.Parallel()

	if len(fanclashCacheAllColumns) == len(fanclashCachePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := FanclashCache{}
	if err = randomize.Struct(seed, &o, fanclashCacheDBTypes, true); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	tx := MustTx(boil.Begin())
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert FanclashCache: %s", err)
	}

	count, err := FanclashCaches().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, fanclashCacheDBTypes, false, fanclashCachePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize FanclashCache struct: %s", err)
	}

	if err = o.Upsert(tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert FanclashCache: %s", err)
	}

	count, err = FanclashCaches().Count(tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
